name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:

# Build
  build:

  runs-on: ubuntu-latest

  steps:

    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -r backend/requirements.txt

# Test
  test:
  
    needs: build

    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run tests
        run: |
          python -m compileall backend
          echo "all test passed !"

# Docker Build and Push 
  docker-build-and-push:

    needs: test

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            phuclegit/backend:latest
            phuclegit/backend:${{ github.sha }}

      - name: Build Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            phuclegit/frontend:latest
            phuclegit/frontend:${{ github.sha }}
# Deploy
  deploy:
    needs: docker-build-and-push

    runs-on: self-hosted

    steps:

      - name: Go to project
        run: |
          cd /home/osboxes/devops/deploy_lab3tier

      - name: Set image tag
        run: |
          cd /home/osboxes/devops/deploy_lab3tier
          sed -i "s/^IMAGE_TAG=.*/IMAGE_TAG=${{ github.sha }}/" .env

      - name: Pull newest images
        run: |
          cd /home/osboxes/devops/deploy_lab3tier
          docker compose -f docker-compose.prod.yml pull

      - name: Restart containers
        run: |
          cd /home/osboxes/devops/deploy_lab3tier
          docker compose -f docker-compose.prod.yml up -d

      - name: Wait application
        run: |
          sleep 15

      - name: Health check
        run: |
          curl -f http://localhost/health