name: Rollback
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image tag (github.sha) to rollback to'
        required: true

jobs:

  rollback:

    runs-on: self-hosted

    steps:

      - name: Go to project
        run: |
          cd /home/osboxes/devops/deploy_lab3tier

      - name: Set image tags
        run: |
          echo "IMAGE_TAG = ${{ github.event.inputs.version }}" > .env

      - name: Pull specified images
        run: |
          cd /home/osboxes/devops/deploy_lab3tier
          docker compose -f docker-compose.prod.yml pull

      - name: Restart containers
        run: |
          cd /home/osboxes/devops/deploy_lab3tier
          docker compose -f docker-compose.prod.yml up -d

      - name: Wait application
        run: |
          sleep 15

      - name: Health check
        run: |
          curl -f http://localhost/health